-- ============================================================
-- Migration: Create assets table for Vercel Postgres (Neon)
-- Run this in the Neon SQL editor after provisioning Postgres.
-- ============================================================

CREATE TABLE IF NOT EXISTS assets (
  -- Common fields
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       VARCHAR(128) NOT NULL DEFAULT 'local-user',
  type          VARCHAR(20)  NOT NULL CHECK (type IN ('physical', 'digital_game', 'subscription')),

  name          VARCHAR(255) NOT NULL,
  category      VARCHAR(100) NOT NULL,
  tags          JSONB        NOT NULL DEFAULT '[]',
  price         NUMERIC(12,2) NOT NULL DEFAULT '0',
  purchase_date VARCHAR(20),

  image_urls    JSONB        NOT NULL DEFAULT '[]',
  note          TEXT,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),

  -- Physical-only
  brand         VARCHAR(255),
  location      VARCHAR(255),
  warranty_end  VARCHAR(20),

  -- Digital-game-only
  platform      VARCHAR(50),
  is_completed  BOOLEAN      DEFAULT FALSE,

  -- Subscription-only
  billing_cycle VARCHAR(20),
  next_billing  VARCHAR(20),
  auto_renew    BOOLEAN      DEFAULT TRUE
);

-- Index for quick user-scoped queries
CREATE INDEX IF NOT EXISTS idx_assets_user_id ON assets (user_id);

-- Index for listing sorted by creation date
CREATE INDEX IF NOT EXISTS idx_assets_created_at ON assets (created_at DESC);

-- Index for filtering by type
CREATE INDEX IF NOT EXISTS idx_assets_type ON assets (type);